# Generated by Django 4.0.4 on 2022-05-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_point_name', models.CharField(max_length=255, verbose_name='Наименование торговой точки')),
            ],
            options={
                'verbose_name': 'Торговые точки',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('worker_phone', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('sale_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_api.salepoint', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Посещения',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.AddField(
            model_name='salepoint',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_api.worker', verbose_name='Сотрудник'),
        ),
    ]
